In [26]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [27]:
arr.shape

(3, 3)

In [28]:
arr.dtype.type

numpy.int32

In [29]:
type(arr)

numpy.ndarray

Array Operation and Manipulations

In [30]:
zero = np.zeros((2,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.]])

In [31]:
ones = np.ones((2,2))
ones

array([[1., 1.],
       [1., 1.]])

In [32]:
range_arr = np.arange(0,10,2)
range_arr

array([0, 2, 4, 6, 8])

In [33]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,4,8,9,5])
print(a1+a2)

[ 7  6 11 13 10]


LAB 1

1. Generate a 1D array ranging from 1 to 20

In [34]:
import numpy as np

arr = np.arange(1,10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
reshape = arr.reshape(3,3)
reshape

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
reshape.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

Broadcasting

In [37]:
arr1d = np.array([1,2,3])
arr2d = np.array([[1],[2],[3]])
arr1d + arr2d

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

1. Create a ID array from 1 to IO, Print it
2. Reshape the ID array into a 2x5 2D array & Print it
3. Retrieve the element in the first row, third
column of the 2D array, print the element

In [38]:
arr = np.arange(1,11)
reshape = arr.reshape(2,5)
reshape

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
reshape[(0,2)]

3

In [40]:
arr = np.array([1,2,3,4,5,6,7])
print(arr.min())
print(arr.max())
print(arr.std())
print(arr.sum())

1
7
2.0
28


4. Change the values in the first row of the array to 0
5. create another 2x5 array with all values equal to 0
6. create another 2x3 array with all values equal to 2
7. multiply the original array by this new array
8. Find the sum of all elements in the array generated in step 7

In [41]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])
arr[0]=0
arr

array([[0, 0, 0],
       [1, 2, 3],
       [1, 2, 3]])

In [42]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [43]:
arr = np.zeros((2,3),dtype=int)
arr = arr+2
arr

array([[2, 2, 2],
       [2, 2, 2]])

In [44]:
og  = np.arange(1,11)
print(og)
print(arr)


[ 1  2  3  4  5  6  7  8  9 10]
[[2 2 2]
 [2 2 2]]


Rules of Broadcasting
1. Shape Compatibility: Two dimension are compatible if they are equal, or one of them is 1.
2. Dimension Addition: If arrays have different numbers of dimensions, Numpy "adds" dimensions of size 1 to the left of
the smaller arrays shape.
3. Stretching: if a dimension in one array is 1, it can be stretched to match the other array.

Shape Error, can't solve 7 and 8

Labs
1. generate an array from 1 to 50
2. calculate the mean, standard deviation, maximum and minimum
3. create a 2x5 array and flatten it into a ID array
4. use boolean indexing to extract all elements greater than 45
5. Create a new array containing values [ 11,12,13,141 concatenate this with the orginial array in task 1
6. reshape the array from task 5 into a 2x2 array.

In [45]:
arr = np.arange(1,51)
print(arr)
print(arr.mean())
print(arr.std())
print(arr.max())
print(arr.min())

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]
25.5
14.430869689661812
50
1


In [46]:
arr2 = np.ones((2,5),dtype=int)
arr2.flatten()

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [47]:
arr3 = [11,12,13,14]
np.concatenate()


TypeError: concatenate() missing 1 required positional argument: 'arrays'

In [ ]:
a = np.array([[1, 2], [3, 4]])
a.shape

(2, 2)

In [ ]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
b = np.array([10])
a+b

array([[11, 12],
       [13, 14]])

In [ ]:
a = np.arange(0,16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])