Numpy - Numerical Python

In [26]:
import numpy as np

arr = np.array([5,3,2])

In [27]:
arr+1

array([6, 4, 3])

In [33]:
arr1 = [1,2,3,4,5]
narr = np.array(arr1,copy=False)

array([1, 2, 3, 4, 5])

Task I: Create a ID Numpy array 12 values for each month, name
of the variable should be "monthly_sales"

In [39]:
monthly_sales = [5977,  231, 6574, 8963,  869, 2168,  112, 3722, 4009, 7620, 3533,
       7427]
arr = np.array(monthly_sales)

Task 2: 
1 -Access and print the sales data for January (the first month)
2. Accesss and print the data for December (the last month).


In [60]:
print("Jan Info",arr[0])
print("Dec info",arr[-1])

Jan Info 5977
Dec info 7427


Task 3: 1. Extract and print the sales data for each quarter (QI, Q2, Q3, Q4).

In [61]:
print("Q1")
print(arr[:3])
print("Q2")
print(arr[3:6])
print("Q3")
print(arr[6:9])
print("Q4")
print(arr[9:])

Q1
[5977  231 6574]
Q2
[8963  869 2168]
Q3
[ 112 3722 4009]
Q4
[7620 3533 7427]
