LAB
1 . Create a Multidimensional Array
2. Access the 2nd element in the Array
3. Access the 3rd element inside the 2nd Array

In [7]:
import numpy as np

arr = np.array([[5,3,2],[7,3,4],[1,3,2]])
arr[2][1]
arr[1][2]

4

In [8]:
arr = np.array([1,2,3,4,5,6,7,8,9,1,2,3,4,5,6,7,8])
arr[:5]

array([1, 2, 3, 4, 5])

I. Create Montly Revenue array
2. Enter 12 elements
3. slice last 4 elements in that array

In [11]:
monthly_revenue = [123,324,463,686,423,999,535,333,987,678,443,123]
monthly_revenue[-4:]

[987, 678, 443, 123]

In [20]:
stop = 200
np.mean(monthly_revenue)
print([revenue for revenue in monthly_revenue if revenue < stop])

[123, 123]


1. Create Monthly_Sales Numpy array
2. Add values for each month
3. Modify the Data entry for the Month of April
4. Extract and print the sales data for the summer months (June, July, August)
5. Calculate and print the average sales for the summer months
6. Calculate the average monthly sales for the entire year
7. Identify and print the months where the sales were above average

In [31]:
import random 
monthly_revenue = np.array([],dtype=int)

for i in range(0,12):
    num = random.randint(100,500)
    monthly_revenue = np.append(monthly_revenue, num)
    
print(monthly_revenue)
monthly_revenue[3] =100

print(monthly_revenue[5:8])

print(np.mean(monthly_revenue[5:8]))

avg = np.mean(monthly_revenue)

print(monthly_revenue[monthly_revenue > avg])
   

[431 277 382 415 321 116 355 419 255 466 235 139]
[116 355 419]
296.6666666666667
[431 382 321 355 419 466]
