In [ ]:
import numpy as np

print(np.__version__)

In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [4]:
import numpy as np

a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [5]:
import numpy as np

arr = np.array([1,2,3,4,5], ndmin=5)
print(arr)
print("Dimensions of array: ",arr.ndim)

[[[[[1 2 3 4 5]]]]]
Dimensions of array:  5


In [6]:
import numpy as np

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[1:4:2])
#arr[start:end:step]->slicing with start end and step

[2 4]


In [8]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[:4])

[1 2 3 4]


In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr[4:])

[5]


In [10]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[-3:-1])

[5 6]


In [12]:
import numpy as np

arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:4])

[7 8 9]


In [14]:
monthly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(monthly_sales[0])
print(monthly_sales[-1])

1
12


In [21]:
monthly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(f"1st Quarter: {monthly_sales[:3]}")
print(f"2nd Quarter: {monthly_sales[3:6]}")
print(f"3rd Quarter: {monthly_sales[6:9]}")
print(f"4th Quarter: {monthly_sales[9:]}")

1st Quarter: [1 2 3]
2nd Quarter: [4 5 6]
3rd Quarter: [7 8 9]
4th Quarter: [10 11 12]


In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[0:2, 2])

[3 8]


In [14]:
import numpy as np
sales_data = np.array([[200,220,250],[210,230,275],[190,205,235]])
print(sales_data[0,1])
print(sales_data[0,0:5])

220
[[200 220 250]
 [210 230 275]
 [190 205 235]]


In [17]:
import numpy as np
farr = np.array([1.1,2.1,3.5])
iarr = farr.astype('i')
print(farr)
print(iarr)

[1.1 2.1 3.5]
[1 2 3]


In [18]:
import numpy as np
monthly_revenue = [1,2,3,4,5,6,7,8,9,10,11,12]
print(monthly_revenue[-4:])

[9, 10, 11, 12]


In [19]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype(int)

print(newarr)
print(newarr.dtype)


[1 2 3]
int64


In [21]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [23]:
monthly_sales = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
x = int(input("Enter the sales in the month of April:"))
monthly_sales[3] = x

print(monthly_sales[5:8])
avg = np.mean(monthly_sales[5:8])
print(f"The average sales in the summer months is:{avg}")
print(f"The average sales for the year is:{np.mean(monthly_sales)}")
print(monthly_sales[monthly_sales>np.mean(monthly_sales)])


[6 7 8]
The average sales in the summer months is:7.0
The average sales for the year is:7.0
[10  8  9 10 11 12]


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [8]:
import numpy as np
arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [9]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [10]:
import numpy as np
arr = np.arange(0,21)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

<built-in method reshape of numpy.ndarray object at 0x00000257FA2C7810>


In [14]:
import numpy as np

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [19]:
import numpy as np
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr = arr.reshape(4,3)
newnew = arr.reshape(2,3,2)
print(newarr)
print(newnew)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [20]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(3, 3)
print(newarr)

ValueError: cannot reshape array of size 8 into shape (3,3)

In [21]:
#reshape provides view and not a copy
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr.reshape(2, 4).base)


[1 2 3 4 5 6 7 8]


In [22]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [24]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [36]:
import numpy as np
arr = np.arange(1,11)
newarr = arr.reshape(2,5)
print(newarr)
print(newarr[0][2])
print(newarr[0])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
[1 2 3 4 5]


In [42]:
import numpy as np
arr = np.arange(1,11)
arr = arr.reshape(2,5)
print(arr)
print(arr[0][2])
arr[0] = 0
newarr = np.zeros([2,5])
newnewarr = np.array([2,2,2,2,2,2])
newnewarr = newnewarr.reshape(2,3)
# mul = arr * newnewarr
# print(mul)
print(np.sum(arr))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3
40
